controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

simple_velocity_broadcaster:
  ros__parameters:
    type: velocity_controller/JointGroupVelocityController
    joints:
      - wheel_right_joint
      - wheel_left_joint
